# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 645)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_numerical_analysis = QtWidgets.QLabel(self.centralwidget)
        self.label_numerical_analysis.setGeometry(QtCore.QRect(110, 10, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_numerical_analysis.setFont(font)
        self.label_numerical_analysis.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_numerical_analysis.setObjectName("label_numerical_analysis")
        self.button_0 = QtWidgets.QPushButton(self.centralwidget)
        self.button_0.setGeometry(QtCore.QRect(200, 460, 93, 28))
        self.button_0.setObjectName("button_0")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(90, 420, 93, 28))
        self.button_1.setObjectName("button_1")
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(200, 420, 93, 28))
        self.button_2.setObjectName("button_2")
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setGeometry(QtCore.QRect(310, 420, 93, 28))
        self.button_3.setObjectName("button_3")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setGeometry(QtCore.QRect(90, 380, 93, 28))
        self.button_4.setObjectName("button_4")
        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5.setGeometry(QtCore.QRect(200, 380, 93, 28))
        self.button_5.setObjectName("button_5")
        self.button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6.setGeometry(QtCore.QRect(310, 380, 93, 28))
        self.button_6.setObjectName("button_6")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7.setGeometry(QtCore.QRect(90, 340, 93, 28))
        self.button_7.setObjectName("button_7")
        self.button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_8.setGeometry(QtCore.QRect(200, 340, 93, 28))
        self.button_8.setObjectName("button_8")
        self.button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.button_9.setGeometry(QtCore.QRect(310, 340, 93, 28))
        self.button_9.setObjectName("button_9")
        self.button_cosine = QtWidgets.QPushButton(self.centralwidget)
        self.button_cosine.setGeometry(QtCore.QRect(90, 160, 93, 28))
        self.button_cosine.setObjectName("button_cosine")
        self.button_sine = QtWidgets.QPushButton(self.centralwidget)
        self.button_sine.setGeometry(QtCore.QRect(200, 160, 93, 28))
        self.button_sine.setObjectName("button_sine")
        self.tan = QtWidgets.QPushButton(self.centralwidget)
        self.tan.setGeometry(QtCore.QRect(310, 160, 93, 28))
        self.tan.setObjectName("tan")
        self.button_exp = QtWidgets.QPushButton(self.centralwidget)
        self.button_exp.setGeometry(QtCore.QRect(90, 200, 93, 28))
        self.button_exp.setObjectName("button_exp")
        self.button_x_variable = QtWidgets.QPushButton(self.centralwidget)
        self.button_x_variable.setGeometry(QtCore.QRect(90, 240, 93, 28))
        self.button_x_variable.setObjectName("button_x_variable")
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setGeometry(QtCore.QRect(200, 240, 93, 28))
        self.button_plus.setObjectName("button_plus")
        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus.setGeometry(QtCore.QRect(310, 240, 93, 28))
        self.button_minus.setObjectName("button_minus")
        self.button_mult = QtWidgets.QPushButton(self.centralwidget)
        self.button_mult.setGeometry(QtCore.QRect(200, 200, 93, 28))
        self.button_mult.setObjectName("button_mult")
        self.button_divide = QtWidgets.QPushButton(self.centralwidget)
        self.button_divide.setGeometry(QtCore.QRect(310, 200, 93, 28))
        self.button_divide.setObjectName("button_divide")
        self.functionField = QtWidgets.QLineEdit(self.centralwidget)
        self.functionField.setGeometry(QtCore.QRect(90, 90, 311, 41))
        self.functionField.setObjectName("functionField")
        self.button_method_bisection = QtWidgets.QPushButton(self.centralwidget)
        self.button_method_bisection.setGeometry(QtCore.QRect(540, 80, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_method_bisection.setFont(font)
        self.button_method_bisection.setObjectName("button_method_bisection")
        self.button_method_fixedPoint = QtWidgets.QPushButton(self.centralwidget)
        self.button_method_fixedPoint.setGeometry(QtCore.QRect(540, 230, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_method_fixedPoint.setFont(font)
        self.button_method_fixedPoint.setObjectName("button_method_fixedPoint")
        self.button_method_falsePosition = QtWidgets.QPushButton(self.centralwidget)
        self.button_method_falsePosition.setGeometry(QtCore.QRect(540, 120, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_method_falsePosition.setFont(font)
        self.button_method_falsePosition.setObjectName("button_method_falsePosition")
        self.button_method_secant = QtWidgets.QPushButton(self.centralwidget)
        self.button_method_secant.setGeometry(QtCore.QRect(540, 310, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_method_secant.setFont(font)
        self.button_method_secant.setObjectName("button_method_secant")
        self.button_method_newtonRaphson = QtWidgets.QPushButton(self.centralwidget)
        self.button_method_newtonRaphson.setGeometry(QtCore.QRect(540, 270, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_method_newtonRaphson.setFont(font)
        self.button_method_newtonRaphson.setObjectName("button_method_newtonRaphson")
        self.button_READ = QtWidgets.QPushButton(self.centralwidget)
        self.button_READ.setGeometry(QtCore.QRect(640, 500, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_READ.setFont(font)
        self.button_READ.setObjectName("button_READ")
        self.button_power = QtWidgets.QPushButton(self.centralwidget)
        self.button_power.setGeometry(QtCore.QRect(90, 280, 93, 28))
        self.button_power.setObjectName("button_power")
        self.button_left_bracket = QtWidgets.QPushButton(self.centralwidget)
        self.button_left_bracket.setGeometry(QtCore.QRect(200, 280, 93, 28))
        self.button_left_bracket.setObjectName("button_left_bracket")
        self.button_right_bracket = QtWidgets.QPushButton(self.centralwidget)
        self.button_right_bracket.setGeometry(QtCore.QRect(310, 280, 93, 28))
        self.button_right_bracket.setObjectName("button_right_bracket")
        self.button_dot = QtWidgets.QPushButton(self.centralwidget)
        self.button_dot.setGeometry(QtCore.QRect(90, 460, 93, 28))
        self.button_dot.setObjectName("button_dot")
        self.label_x_up = QtWidgets.QLabel(self.centralwidget)
        self.label_x_up.setGeometry(QtCore.QRect(550, 180, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_x_up.setFont(font)
        self.label_x_up.setObjectName("label_x_up")
        self.label_x_low = QtWidgets.QLabel(self.centralwidget)
        self.label_x_low.setGeometry(QtCore.QRect(550, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_x_low.setFont(font)
        self.label_x_low.setObjectName("label_x_low")
        self.label_x_initial = QtWidgets.QLabel(self.centralwidget)
        self.label_x_initial.setGeometry(QtCore.QRect(550, 340, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_x_initial.setFont(font)
        self.label_x_initial.setObjectName("label_x_initial")
        self.button_ENTER = QtWidgets.QPushButton(self.centralwidget)
        self.button_ENTER.setGeometry(QtCore.QRect(540, 500, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_ENTER.setFont(font)
        self.button_ENTER.setObjectName("button_ENTER")
        self.lineEdit_iterations = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_iterations.setGeometry(QtCore.QRect(632, 430, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_iterations.setFont(font)
        self.lineEdit_iterations.setObjectName("lineEdit_iterations")
        self.lineEdit_tolerance = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tolerance.setGeometry(QtCore.QRect(632, 400, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_tolerance.setFont(font)
        self.lineEdit_tolerance.setObjectName("lineEdit_tolerance")
        self.lineEdit_x_low = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_x_low.setGeometry(QtCore.QRect(630, 160, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_x_low.setFont(font)
        self.lineEdit_x_low.setObjectName("lineEdit_x_low")
        self.lineEdit_x_up = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_x_up.setGeometry(QtCore.QRect(630, 190, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_x_up.setFont(font)
        self.lineEdit_x_up.setObjectName("lineEdit_x_up")
        self.lineEdit_x_initial = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_x_initial.setGeometry(QtCore.QRect(630, 350, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_x_initial.setFont(font)
        self.lineEdit_x_initial.setObjectName("lineEdit_x_initial")
        self.label_iteration = QtWidgets.QLabel(self.centralwidget)
        self.label_iteration.setGeometry(QtCore.QRect(540, 420, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_iteration.setFont(font)
        self.label_iteration.setObjectName("label_iteration")
        self.label_tolerance = QtWidgets.QLabel(self.centralwidget)
        self.label_tolerance.setGeometry(QtCore.QRect(540, 390, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_tolerance.setFont(font)
        self.label_tolerance.setObjectName("label_tolerance")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(520, 210, 211, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(520, 370, 211, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(460, 70, 20, 491))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.button_pi = QtWidgets.QPushButton(self.centralwidget)
        self.button_pi.setGeometry(QtCore.QRect(310, 460, 93, 28))
        self.button_pi.setObjectName("button_pi")
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(310, 520, 93, 28))
        self.button_delete.setObjectName("button_delete")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(90, 520, 93, 28))
        self.button_clear.setObjectName("button_clear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_numerical_analysis.setText(_translate("MainWindow", "Numerical Analysis"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_cosine.setText(_translate("MainWindow", "cos"))
        self.button_sine.setText(_translate("MainWindow", "sin"))
        self.tan.setText(_translate("MainWindow", "tan"))
        self.button_exp.setText(_translate("MainWindow", "e"))
        self.button_x_variable.setText(_translate("MainWindow", "x"))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_mult.setText(_translate("MainWindow", "*"))
        self.button_divide.setText(_translate("MainWindow", "/"))
        self.button_method_bisection.setText(_translate("MainWindow", "Bisection"))
        self.button_method_fixedPoint.setText(_translate("MainWindow", "Fixed-Point"))
        self.button_method_falsePosition.setText(_translate("MainWindow", "False Position"))
        self.button_method_secant.setText(_translate("MainWindow", "Secant"))
        self.button_method_newtonRaphson.setText(_translate("MainWindow", "Newton-Raphson"))
        self.button_READ.setText(_translate("MainWindow", "Read file"))
        self.button_power.setText(_translate("MainWindow", "^"))
        self.button_left_bracket.setText(_translate("MainWindow", "("))
        self.button_right_bracket.setText(_translate("MainWindow", ")"))
        self.button_dot.setText(_translate("MainWindow", "."))
        self.label_x_up.setText(_translate("MainWindow", "X(u) ="))
        self.label_x_low.setText(_translate("MainWindow", "X(l)  ="))
        self.label_x_initial.setText(_translate("MainWindow", "X(i) ="))
        self.button_ENTER.setText(_translate("MainWindow", "Enter"))
        self.lineEdit_iterations.setText(_translate("MainWindow", "50"))
        self.lineEdit_tolerance.setText(_translate("MainWindow", "0.0001"))
        self.lineEdit_x_low.setText(_translate("MainWindow", "0"))
        self.lineEdit_x_up.setText(_translate("MainWindow", "0"))
        self.lineEdit_x_initial.setText(_translate("MainWindow", "0"))
        self.label_iteration.setText(_translate("MainWindow", "iterations:"))
        self.label_tolerance.setText(_translate("MainWindow", "tolerance:"))
        self.button_pi.setText(_translate("MainWindow", "π"))
        self.button_delete.setText(_translate("MainWindow", "DEL"))
        self.button_clear.setText(_translate("MainWindow", "CLEAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

